language: node_js
node_js:
- '6'
# Cache our Gcloud SDK between commands
# cache:
#   directories:
#   - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
skip_files:
- dummy
before_install:
- openssl aes-256-cbc -K $encrypted_b8ef22b72338_key -iv $encrypted_b8ef22b72338_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
# - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# - rm -rf $HOME/google-cloud-sdk
# - curl https://sdk.cloud.google.com | bash
- tar -xzf credentials.tar.gz
- mkdir -p ghost
# - ls ${HOME}/google-cloud-sdk/bin
# - which gcloud
# - gcloud version
# # Here we use the decrypted service account credentials to authenticate the command line tool
# - gcloud auth activate-service-account --key-file client-secret.json
install:
# - sudo npm install -g ghost-cli@latest
- yarn global add ghost-cli@latest
# - yarn add ghost-cli@latest
- cd ghost
# - which ghost
- whoami
- npm root -g
# - ls -al /home/travis/.nvm/versions/node/v6.11.3/
# - npm root -g | xargs sudo chmod -R 755 
# - ../node_modules/ghost-cli/bin/ghost install --no-prompt
- ghost install --url=https://hellojcc-178809.appspot.com --host=0.0.0.0 --db sqlite3 --dbpath ./content/data/ghost.db --no-prompt --no-stack --no-setup-linux-user --no-setup-mysql --no-setup-nginx --no-setup-systemd --no-setup-migrate
- ls -al
- ls -al current/node_modules
- cp ../config.*.json ./
- cd content/themes
- git clone -b jcc-v2 https://github.com/ddhp/Casper.git casper-jcc
- cd ../../../
- ls -al
script: 
deploy:
  provider: gae
  # Skip cleanup so api_key.py and vendored dependencies are still there
  skip_cleanup: true
  keyfile: "client-secret.json"
  project: "hellojcc-178809"
  default: true
  on:
    all_branches: true
